// Do not edit manually

export const IMAGES = {
  ANIMA_19: "/images/anima.png",
  CEA_18: "/images/cea.png",
  COINBASE_26: "/images/coinbase.png",
  EPIC_25: "/images/epic.png",
  FLAM_33: "/images/flam.png",
  GPA_17: "/images/gpa.png",
  GREENP_16: "/images/greenp.png",
  HERING_15: "/images/hering.png",
  IMG_10_38: "/images/10.png",
  IMG_11_55: "/images/11.png",
  IMG_12_57: "/images/12.png",
  IMG_13_53: "/images/13.png",
  IMG_14_47: "/images/14.png",
  IMG_15_52: "/images/15.png",
  IMG_16_49: "/images/16.png",
  IMG_17_50: "/images/17.png",
  IMG_18_48: "/images/18.png",
  IMG_19_42: "/images/19.png",
  IMG_1_54: "/images/1.png",
  IMG_20_46: "/images/20.png",
  IMG_21_41: "/images/21.png",
  IMG_2_51: "/images/2.png",
  IMG_3_56: "/images/3.png",
  IMG_4_45: "/images/4.png",
  IMG_5_44: "/images/5.png",
  IMG_6_43: "/images/6.png",
  IMG_7_40: "/images/7.png",
  IMG_8_39: "/images/8.png",
  IMG_9_37: "/images/9.png",
  ITAU_14: "/images/itau.png",
  LOGO_WQI_BRANCO: "/images/wqi branco.png",
  LOGO_WQI_COLOR: "/images/wqi copper.png",
  MCD_13: "/images/mcd.png",
  MULTIP_32: "/images/multip.png",
  NIVEA_36: "/images/nivea.png",
  NVIDIA_28: "/images/nvidia.png",
  PARALLAX_AI_MARKETING: "/images/1715.jpg",
  PARALLAX_AI_PRESENTATION: "/images/11548.jpg",
  PARALLAX_EXECUTIVE: "/images/105957.jpg",
  PARALLAX_HANDSHAKE_ROBOT: "/images/1662.jpg",
  PARALLAX_HOLOGRAPHIC: "/images/1657.jpg",
  PARALLAX_HUMAN_ROBOT: "/images/1439.jpg",
  PEPSI_24: "/images/pepsi.png",
  PUBLI_23: "/images/publi.png",
  REMAX_31: "/images/remax.png",
  SALTA_35: "/images/salta.png",
  SAMS_22: "/images/sams.png",
  SG_27: "/images/sg.png",
  SHOPIFY_34: "/images/shopify.png",
  SPOTIFY_30: "/images/spotify.png",
  STONE_21: "/images/stone.png",
  TOM_HERO_BG: "/images/tom speaking 11.png",
  TOM_HERO_PORTRAIT: "/images/1.png",
  TOM_PROFILE_ALT: "/images/magnific_photo-a-40yearold-middle-_2905621111.png",
  TOM_SOBRE: "/images/tom speaking 11.png",
  TOM_SPEAKING_YOUNG_58: "/images/tom speaking young.png",
  UNIVERSAL_20: "/images/universal.png",
  WMC_29: "/images/wmc.png",
} as const;

export type ImageKey = keyof typeof IMAGES;
